version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-employee_tracking}
      - POSTGRES_USER=${DB_USER:-django_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mysecretpassword}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-django_user} -d ${DB_NAME:-employee_tracking}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
